# Logging pattern containing traceId and spanId; no longer provided through Sleuth by default
logging.pattern.level="%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
spring.main.web-application-type=none
spring.profiles.active=${ACTIVE_PROFILES_SPRING:disable-security}