jdbc.Url=${jdbc.Url}
jdbc.User=${jdbc.User}
jdbc.Password=${jdbc.Password}
# Logging pattern containing traceId and spanId; no longer provided through Sleuth by default
logging.pattern.level="%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
spring.profiles.active=${ACTIVE_PROFILES_SPRING:disable-security}
